### ISSUE TITLE
Issue Security mapping exception since >= 1.19.8

### ISSUE THREAD

**Issue by Dave13h** [lesstif/php-jira-rest-client#148]
Hi, 

When I ```get()``` an issue using the ```JiraIssueService``` and the issue has a security level set in Jira, I am seeing this exception coming through. 

```
Uncaught Exception ReflectionException: "Class \JiraRestApi\Issue\$securityId does not exist" at [...]/vendor/netresearch/jsonmapper/src/JsonMapper.php line 556
```

Rolling back to version 1.19.7 seems to work fine again, I can see there were a few changes in the newer versions around the security fields. I'm guessing something isn't translating into the JsonMapper correctly?

Cheers
Dave

**Comment by lesstif** [comment]
i'm sorry, it's my mistake. 

the security scheme field possibly to null value, but mapping rule haven't it.

it was fixed at [v1.20.1](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.20.1).

thanks

**Comment by Dave13h** [comment]
Thanks for the quick reply. I've updated to 1.20.1 but I still get the same exception.

```
lesstif/php-jira-rest-client        1.20.1             JIRA REST API Client for PHP Users.
```

```"Class \JiraRestApi\Issue\$securityId does not exist"```

The Issue I am ```get()```ing actually has a security level set on it, so it shouldn't be null.

Dave

**Comment by lesstif** [comment]
could you emailing to me with the server's response json data?

**Comment by zhutik** [comment]
On `1.20.1` I also see an issue

```
JSON property "security" in class "JiraRestApi\Issue\IssueField" must not be NULL
```

**Comment by lesstif** [comment]
@zhutik Thank you for your kind explanation.

it was fixed in the [1.20.2](https://github.com/lesstif/php-jira-rest-client/releases/tag/1.20.2).

thanks~
